### ISSUE TITLE
select distinct gradyear, majorid, count(sid) from student, dept where sid >= 1 and majorid = did group by gradyear, majorid, did order by gradyear asc, majorid desc, count(sid) desc

### ISSUE THREAD

**Issue by tjwjoe** [LimZeWeiDennis/CS3223-Group27#12]
Query `select distinct gradyear, majorid, count(sid) from student, dept where sid >= 1 and majorid = did group by gradyear, majorid, did order by gradyear asc, majorid desc, count(sid) desc` throws BadSyntaxException

**Comment by LimZeWeiDennis** [comment]
require changing of column naming in the agg fns
